import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import SmoothScrolling from "@/lib/animations/SmoothScrolling";

const sansationRegFont = localFont({ src: './Sansation-Regular.ttf' });

export const metadata: Metadata = {
  title: "Bizniz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`bg-[#ffff] text-black antialiased ${sansationRegFont.className}`} // Apply the regular font here
      >
        <SmoothScrolling>
            {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
